apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-test-deploy
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: k8s-test
    spec:
      containers:
      - name: my-shopping-cart
        image: pranaya88/k8s_test_cart1:v1
        ports:
        - containerPort: 8080