apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  selector:
    matchLabels:
      app: shopping-cart
      department: sales
  replicas: 3
  template:
    metadata:
      labels:
        app: shopping-cart
        department: sales
    spec:
      containers:
      - name: my-shopping-cart
        image: pranaya88/k8s_test_cart:V1
        ports:
        - containerPort: 8080