apiVersion: v1
kind: Service
metadata:
  name: k8s-test-deploy-svc
  labels:
    app: k8s-test
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
  selector:
    app: k8s-test