apiVersion: v1
kind: Service
metadata:
  name: k8s-test-deploy-svc
  labels:
    app: K8-test-deploy
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
  selector:
    app: K8-test-deploy